name: movie_findr
description: A Flutter application that helps users discover movie recommendations based on their preferences.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  riverpod: ^2.6.1
  flutter_riverpod: ^2.6.1
  equatable: ^2.0.7
  dio: ^5.8.0+1
  pretty_dio_logger: ^1.4.0
  multiple_result: ^5.2.0
  skeletonizer: ^1.4.3
  go_router: ^15.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  mocktail: ^1.0.4
  flutter_lints: ^5.0.0
  rps: ^0.7.0

# Scripts that can be run with "Dart run rps <script>"
scripts:
  # Integration tests
  integration: flutter drive --driver=test_driver/integration_test.dart --target=integration_test/movie_feature_test.dart

  # Unit tests
  test: flutter test
  test:watch: flutter test --watch

  # Build and run
  build:android: flutter build apk --release
  build:ios: flutter build ios --release
  clean: flutter clean

  # Linting
  lint: flutter analyze

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
